[project]
    dependencies    = [  ]
    description     = "Add your description here"
    name            = "pray"
    readme          = "README.md"
    requires-python = ">=3.13"
    version         = "0.1.0"

[dependency-groups]
    dev = [ "ipykernel>=6.29.5" ]
